---
- name: Get Hostname and other commands
  hosts: all
  gather_facts: no
  connection: network_cli

  vars_prompt:
    - name: "ansible_user"
      prompt: "Enter Authorized Username"
      private: no   # So they can see what they type
    - name: "ansible_password"
      prompt: "Enter Authorized Password"
      private: yes  # Hides the password (standard)
  tasks:
    - name: Get Commands from Cisco AP
      cisco.ios.ios_command:
        commands:
          - show running-config | include hostname
          - show running-config | include snmp
          - show ip interface brief
          - show ip ssh
          - show running-config | include aaa new-model
          - show version

      register: commands_output

    - name: Display Device Information
      debug:
        msg:
          - "========================================================="
          - "                ACCESS POINT CONFIGURATIONS                     "
          - "========================================================="
          - "1. HOSTNAME:"
          - "{{ commands_output.stdout[0] }}"
          - " "
          - "2. SNMP STATUS AND CONFIGURATION:"
          - "{{ commands_output.stdout[1] }}"
          - " "
          - "3. IP INTERFACE BRIEF:"
          - "{{ commands_output.stdout[2] }}"
          - " "
          - "4. SSH STATUS:"
          - "{{ commands_output.stdout[3] }}"
          - " "
          - "5. AAA STATUS:"
          - "{{commands_output[4]}}"
          - " "
          - "6. Version of the Device"
          - "{{command_output[5]}}"
          - " "
          - "========================================================="

