name: Ansible CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  syntax-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Ansible
        run: |
          pip install ansible

      - name: Run Ansible syntax check
        run: |
          ansible-playbook config.yml --syntax-check \
          -e "ansible_network_os=cisco.ios.ios" |
          ansible-playbook playbook.yml --syntax-check \ -e "ansible_network_os=cisco.ios.ios" |
          ansible-playbook check_ap.yml --syntax-check \ -e "ansible_network_os=cisco.ios.ios"
