name: Ansible CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        run: |
          pip install ansible ansible-lint

      - name: Lint Ansible Playbook
        # This will check for those blank lines and truthy errors
        run: ansible-lint *.yml 

      - name: Run Syntax Check
        # Validates logic without actually connecting to your devices
        run: ansible-playbook config.yml --syntax-check -e "ansible_network_os=cisco.ios.ios"
